
package Gui;

import Model.MessageDialog;

/**
 *
 * @author audreynaila
 */
public class HomeOrder extends javax.swing.JFrame {
      private String loggedInUsername;
      
       public void setLoggedInUsername(String username) {
        this.loggedInUsername = username;
    }

    public HomeOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnreview = new javax.swing.JButton();
        ordercoffe = new javax.swing.JButton();
        order = new javax.swing.JButton();
        orderplatter = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/OrderHome.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        btnreview.setText("jButton2");
        getContentPane().add(btnreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 750, 150, 40));

        ordercoffe.setText("order");
        ordercoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordercoffeActionPerformed(evt);
            }
        });
        getContentPane().add(ordercoffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 80, 30));

        order.setText("order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 80, 40));

        orderplatter.setText("]order");
        orderplatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderplatterActionPerformed(evt);
            }
        });
        getContentPane().add(orderplatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 110, 40));

        Logout.setText("LogOut");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 790, 110, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordercoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordercoffeActionPerformed
        OrderCoffe coffe = new OrderCoffe(); 
        coffe.setVisible(true);
        dispose();        
    }//GEN-LAST:event_ordercoffeActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        OrderPlatter platter = new OrderPlatter(); 
        platter.setVisible(true);
        dispose();
    }//GEN-LAST:event_orderActionPerformed

    private void orderplatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderplatterActionPerformed
        OrderBakery bakery = new OrderBakery(); 
        bakery.setVisible(true);
        dispose();
    }//GEN-LAST:event_orderplatterActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Home hm = new Home(); 
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MessageDialog obj = new MessageDialog(this);
       obj.showMessage("Do You Want To Exit ?", "");
       if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            System.out.println("User click ok");
        } else {
            System.out.println("User click cancel");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnreview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton order;
    private javax.swing.JButton ordercoffe;
    private javax.swing.JButton orderplatter;
    // End of variables declaration//GEN-END:variables

   
}
