
package Gui;

/**
 *
 * @author audreynaila
 */

import Connection.ConnectionManager;
import Model.MessageDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;



public class Login extends javax.swing.JFrame {

    private Object tf_Username;
    private boolean False;
    private boolean True;
    private Object password;
    private HomeOrder homeOrder;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        username1 = new javax.swing.JTextField();
        ps = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        forgotpas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        lb_showPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        username1.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 780, 90));

        ps.setFont(new java.awt.Font("SansSerif", 0, 28)); // NOI18N
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 780, 90));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Login.png"))); // NOI18N
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forgotpas.setText("jButton3");
        forgotpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasActionPerformed(evt);
            }
        });
        getContentPane().add(forgotpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 170, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 40, -1, 30));

        signup.setText("signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 770, 330, 110));

        login.setText("login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 320, 80));

        lb_showPassword.setText("jLabel1");
        lb_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(lb_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 90, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                String username = username1.getText();
                String password = ps.getText();

                // Create an instance of the ConnectionManager class
                ConnectionManager connectionManager = new ConnectionManager();

                try {
                    // Establish a database connection
                    java.sql.Connection connection = connectionManager.logOn();

                    // Create and execute the SQL SELECT statement to check if the username and password exist in the customers table
                    String sql = "SELECT * FROM customers WHERE username = ? AND password = ?";
                    java.sql.PreparedStatement statement = connection.prepareStatement(sql);
                    statement.setString(1, username);
                    statement.setString(2, password);
                    java.sql.ResultSet resultSet = statement.executeQuery();

                    if (resultSet.next()) {
                        // Close the result set, statement, and database connection
                        resultSet.close();
                        statement.close();
                        connectionManager.logOff();

                        // Create an instance of the HomeOrder class
                        HomeOrder homeOrder = new HomeOrder();

                        // Set the username in the HomeOrder class
                        homeOrder.setLoggedInUsername(username);

                        // Create an instance of the PopLog class
                        PopLog popLog = new PopLog(homeOrder);

                        // Close the current form
                        dispose();

                        // Show the PopLog form
                        java.awt.EventQueue.invokeLater(() -> {
                            popLog.setLocationRelativeTo(null); // Set the location of the PopLog form
                            popLog.setVisible(true);
                        });
    } else {
        // Check if the username and password exist in the admins table
        sql = "SELECT * FROM admins WHERE nama = ? AND password = ?";
        statement = connection.prepareStatement(sql);
        statement.setString(1, username);
        statement.setString(2, password);
        resultSet = statement.executeQuery();

        if (resultSet.next()) {
            // Close the result set, statement, and database connection
            resultSet.close();
            statement.close();
            connectionManager.logOff();

            // Create an instance of the AdminForms class
            AdminForms adminForms = new AdminForms();

            // Set the admin username in the AdminForms class
            adminForms.setLoggedInUsername(username);

            // Create an instance of the PopAdmin class
            PopAdmin popAdmin = new PopAdmin(adminForms);
            popAdmin.setVisible(true);

            // Close the current form
            this.dispose();

            // Show the PopAdmin form
            java.awt.EventQueue.invokeLater(() -> {
                popAdmin.setLocationRelativeTo(null); // Set the location of the PopAdmin form
                popAdmin.setVisible(true);

                // Show the AdminForms form after closing the PopAdmin form
                popAdmin.addWindowListener(new WindowAdapter() {
                    public void windowClosed(WindowEvent e) {
                        java.awt.EventQueue.invokeLater(() -> {
                            adminForms.setLocationRelativeTo(null); // Set the location of the AdminForms form
                            adminForms.setVisible(true);
                        });
                    }
                });
            });
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again.");
        }
    }
} catch (java.sql.SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Login failed. Please try again.");
}



    }//GEN-LAST:event_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MessageDialog obj = new MessageDialog(this);
       obj.showMessage("Do You Want To Exit ?", "");
       if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            System.out.println("User click ok");
        } else {
            System.out.println("User click cancel");
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        SignUp sign = new SignUp(); //membuat objek baru dari kelas Home yaitu home1
        sign.setVisible(true); //menampilkan frame Home
        dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
    PopLog popLog = new PopLog(homeOrder);
    popLog.setVisible(true);
    dispose();
  
    }//GEN-LAST:event_loginMouseClicked

    private void lb_showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showPasswordMouseClicked
         
    }//GEN-LAST:event_lb_showPasswordMouseClicked

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
   
    }//GEN-LAST:event_psActionPerformed

    private void forgotpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasActionPerformed
        ForgotPas forgotPas = new ForgotPas();
        forgotPas.setVisible(true);
        dispose();

    }//GEN-LAST:event_forgotpasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotpas;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lb_showPassword;
    private javax.swing.JButton login;
    private javax.swing.JTextField ps;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables

    void setLoggedInUsername(String username) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
