
package Gui;

import Model.MessageDialog;
import Connection.ConnectionManager;
//import Controller.CostumerController;
import Model.MessageDialog;
import Model.ModelCustomers;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.sql.SQLException;


public class SignUp extends javax.swing.JFrame {
    
    
    private Object tf_name;
    private Object nameTextField;
    private Object emailTextField;


    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        password1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 570, 40));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 570, 40));
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 570, 40));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 560, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/SignUp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 60, -1, 40));

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 720, 150, 30));

        btnRegister.setText("jButton2");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 760, 210, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MessageDialog obj = new MessageDialog(this);
       obj.showMessage("Do You Want To Exit ?", "");
       if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            System.out.println("User click ok");
        } else {
            System.out.println("User click cancel");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      Login  loginuser = new Login(); 
        loginuser.setVisible(true); 
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
      String name = name1.getText();
      String email = email1.getText();
      String username = username1.getText();
      String password = password1.getText();

// Create an instance of the ConnectionManager class
ConnectionManager connectionManager = new ConnectionManager();

try {
    // Establish a database connection
    Connection connection = (Connection) connectionManager.logOn();

    // Create and execute the SQL INSERT statement to add a new user to the customers table
    String sql = "INSERT INTO customers (name, email, username, password) VALUES (?, ?, ?, ?)";
    PreparedStatement statement = (PreparedStatement) connection.prepareStatement(sql);
    statement.setString(1, name);
    statement.setString(2, email);
    statement.setString(3, username);
    statement.setString(4, password);
    int rowsInserted = statement.executeUpdate();

    if (rowsInserted > 0) {
        
        // Close the statement and database connection
        
        statement.close();
        connection.close();
        // Create an instance of the HomeOrder class
        Login lg = new Login();

        // Set the username in the HomeOrder class
        lg.setLoggedInUsername(username);

        // Create an instance of the Popup class
        PopSignUp po1 = new PopSignUp(lg);
        po1.setVisible(true);

        // Close the current form
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Sign up failed. Please try again.");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Sign up failed. Please try again.");
}        
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField email1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField password1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
