
package Gui;

/**
 *
 * @author audreynaila
 */

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import Connection.ConnectionManager;
import Model.MessageDialog;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;


public class TabelTransaksi extends javax.swing.JFrame {

    private int totalPembelian;

    
    public TabelTransaksi() {
        initComponents();
        showTableData();
       
    }
    
    private void showTableData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ProductID");
        model.addColumn("Name");
        model.addColumn("Price");
        model.addColumn("Stock");

        // Melakukan koneksi ke database dan mengambil data dari tabel orders_item
        Connection conn = null;
        Statement stmt = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_caferinai", "root", "");
            stmt = conn.createStatement();

            String sql = "SELECT ProductID, Name, Price, Stock FROM orders_items";
            ResultSet rs = stmt.executeQuery(sql);

            // Masukkan data dari ResultSet ke dalam model tabel
            while (rs.next()) {
                String productID = rs.getString("ProductID");
                String name = rs.getString("Name");
                int price = rs.getInt("Price");
                int stock = rs.getInt("Stock");
                model.addRow(new Object[]{productID, name, price, stock});
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        // Set model tabel dengan data dari database
        JTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonCostum4 = new Gui.ButtonCostum();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        Clear = new Gui.ButtonCostum();
        buttonCostum1 = new Gui.ButtonCostum();
        buttonCostum3 = new Gui.ButtonCostum();
        jLabel8 = new javax.swing.JLabel();
        buttonCostum5 = new Gui.ButtonCostum();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(96, 64, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Rinai Cafe.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 510, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -40, 560, 160));

        buttonCostum4.setText("Exit");
        buttonCostum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCostum4ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCostum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 10, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 110));

        jPanel2.setBackground(new java.awt.Color(30, 20, 18));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 202, 169));
        jLabel6.setText("Subtotal");

        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTable);

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        buttonCostum1.setText("Total");
        buttonCostum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCostum1ActionPerformed(evt);
            }
        });

        buttonCostum3.setText("Buy");
        buttonCostum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCostum3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 202, 169));
        jLabel8.setText("Total");

        buttonCostum5.setText("Back To Product");
        buttonCostum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCostum5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCostum1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(buttonCostum5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCostum3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCostum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCostum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCostum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 740, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
      DefaultTableModel model = (DefaultTableModel) JTable.getModel();
model.setRowCount(0); // Menghapus semua baris pada tabel

total.setText(""); // Mengosongkan nilai dari JTextField total
total1.setText(""); // Mengosongkan nilai dari JTextField total1

// Melakukan koneksi ke database
try {
    // Mengatur koneksi database
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_caferinai", "root", "");
    Statement stmt = conn.createStatement();

    // Query untuk menghapus semua data dari tabel orders_items
    String sql = "TRUNCATE TABLE orders_items";
    stmt.executeUpdate(sql);

    // Menampilkan pesan berhasil
    System.out.println("Data pada tabel Item berhasil dihapus.");

    // Menutup statement dan koneksi
    stmt.close();
    conn.close();

    // Menampilkan pesan berhasil di GUI
    JOptionPane.showMessageDialog(this, "Data pada tabel Item berhasil dihapus dan tabel telah diperbarui.");

} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_ClearActionPerformed

    private void buttonCostum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCostum4ActionPerformed
             MessageDialog obj = new MessageDialog(this);
       obj.showMessage("Do You Want To Exit ?", "");
       if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            System.out.println("User click ok");
        } else {
            System.out.println("User click cancel");
        }        
    }//GEN-LAST:event_buttonCostum4ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
  total.setText(Integer.toString(totalPembelian));
     
    }//GEN-LAST:event_total1ActionPerformed

    private void buttonCostum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCostum1ActionPerformed
try {
    // Koneksi ke database
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_caferinai", "root", "");

    // Mengambil total harga dari tabel orders_items
    String selectSql = "SELECT SUM(Price) AS TotalHarga FROM orders_items";
    PreparedStatement selectStmt = (PreparedStatement) conn.prepareStatement(selectSql);
    ResultSet resultSet = selectStmt.executeQuery();

    if (resultSet.next()) {
        int totalHarga = resultSet.getInt("TotalHarga");

        // Menampilkan hasil ke JTextField total1
        total1.setText(Integer.toString(totalHarga));
        total.setText(Integer.toString(totalHarga));
        
    }

    // Menutup koneksi
    resultSet.close();
    selectStmt.close();
    conn.close();
} catch (SQLException ex) {
    ex.printStackTrace();
}

    }//GEN-LAST:event_buttonCostum1ActionPerformed

    private void buttonCostum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCostum3ActionPerformed
    // Melakukan koneksi ke database
Connection conn = null;
Statement stmt = null;
try {
    // Mengatur koneksi database
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_caferinai", "root", "");
    stmt = conn.createStatement();

    // Query untuk menghapus semua data dari tabel orders_items
    String sql = "TRUNCATE TABLE orders_items";
    stmt.executeUpdate(sql);

    // Menampilkan pesan berhasil
    System.out.println("Data pada tabel orders_items berhasil dihapus.");

    // Menutup statement dan koneksi
    stmt.close();
    conn.close();

    // Menghapus semua baris pada tabel
    DefaultTableModel model = (DefaultTableModel) JTable.getModel();
    model.setRowCount(0);

    // Membuka form PopBuy dan menutup form AdminForms
    java.awt.EventQueue.invokeLater(() -> {
        PopBuy popBuy = new PopBuy();
        popBuy.setLocationRelativeTo(null); // Set the location of the PopBuy form
        popBuy.setVisible(true);
    });
    dispose();

} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_buttonCostum3ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        total.setText(Integer.toString(totalPembelian));
        total1.setText(Integer.toString(totalPembelian));
    }//GEN-LAST:event_totalActionPerformed

    private void buttonCostum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCostum5ActionPerformed
      HomeOrder nw = new HomeOrder();
      nw.setVisible(true);
      dispose();

    }//GEN-LAST:event_buttonCostum5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Gui.ButtonCostum Clear;
    private javax.swing.JTable JTable;
    private Gui.ButtonCostum buttonCostum1;
    private Gui.ButtonCostum buttonCostum3;
    private Gui.ButtonCostum buttonCostum4;
    private Gui.ButtonCostum buttonCostum5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    // End of variables declaration//GEN-END:variables

    void setTableModel(DefaultTableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
